[schema.prisma] fix CI/CD error :
Error: Cannot find module '.prisma/client/default'
Require stack:
- /home/circleci/project/node_modules/.pnpm/@prisma+client@6.18.0_prisma@6.18.0_magicast@0.3.5_typescript@5.9.2__typescript@5.9.2/node_modules/@prisma/client/default.js